Added migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -252,17 +252,21 @@ jobs:
       - run:
           name: Run database migrations
           command: |
-            cd backend
+            cd backend/src
             npm install
             npm run migrations > migrations_dump.txt
             cat migrations_dump.txt
       # Send migration status to kvdb.io
       - run:
-          name: Send migration status to kvdb.ij
+          name: Send migration status to kvdb.io
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt;
             then
+              echo "Migration successful"
               curl https://https://kvdb.io/McQbGiQSmDSEvKJhVqyfcn/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            else
+              echo "Migration failed"
+              exit 1
             fi
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
